name: Bonjour # Name of the workflow
on: [push] # This workflow triggers on a push to the repository

jobs:
  Salutations: # Name of the job
    runs-on: ubuntu-latest # The OS where the job runs
    steps:
      - name: Hello # A task to say hello
        env:
          personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour ${personneASaluer}"
        
      - name: L'heure de salutation # Display the time of the previous task
        run: echo "L'heure était $(date)."
